---
title: Home
images:
  - name: Iorad
    description: Pricing and checkout page design
    url: iorad
    mobile: iorad-pricing-laptop-front-1x.png
    tablet: iorad-pricing-laptop-front-1x.png
    laptop: iorad-pricing-laptop-front-1x.png
    desktop: iorad-pricing-laptop-front-1x.png
  - name: OCCRP
    description: Website redesign
    url: occrp
    mobile: occrp-frontpage-mobile-portrait-1x.png
    tablet: occrp-frontpage-mobile-portrait-1x.png
    laptop: occrp-frontpage-mobile-portrait-1x.png
    desktop: occrp-frontpage-mobile-portrait-1x.png
  - name: Anvelocom
    description: E-commerce
    url: anvelocom
    mobile: anvelocom-archive-tablet-portrait-1x.png
    tablet: anvelocom-archive-tablet-portrait-1x.png
    laptop: anvelocom-archive-tablet-portrait-1x.png
    desktop: anvelocom-archive-tablet-portrait-1x.png
  - name: Scatter
    description: Landing and pricing page design
    url: scatter
    mobile: scatter-frontpage-2-desktop-front-1x.png
    tablet: scatter-frontpage-2-desktop-front-1x.png
    laptop: scatter-frontpage-2-desktop-front-1x.png
    desktop: scatter-frontpage-2-desktop-front-1x.png
  - name: Inu Chivu
    description: Artist portfolio
    url: inu
    mobile: inu-menu-white-mobile-portrait-1x.png
    tablet: inu-menu-white-mobile-portrait-1x.png
    laptop: inu-menu-white-mobile-portrait-1x.png
    desktop: inu-menu-white-mobile-portrait-1x.png
  - name: Smuff
    description: E-commerce
    url: smuff
    mobile: smuff-product-tablet-portrait-1x.png
    tablet: smuff-product-tablet-portrait-1x.png
    laptop: smuff-product-tablet-portrait-1x.png
    desktop: smuff-product-tablet-portrait-1x.png
---

{% include "../structures/head.swig" %}
{% include "../structures/header.swig" %}

{% include "../structures/about.swig" %}
{% include "../structures/works.swig" %}

{% include "../structures/footer.swig" %}
