---
title: OCCRP
subtitle: Website redesign
services:
  - Responsive web design
  - Front&mdash;end development
technologies:
  - HTML5
  - CSS3
  - SASS
  - jQuery
description:
  - "Organized Crime And Corruption Reporting Project had it's website dated from the last decade."
  - "We've managed to come up with a modern, newspaper-like redesign with clean headlines, good structure, clean understanding of priorities."
  - "The new site supports all screens from mobile devices up to large projectors."
images:
  - name: The OCCRP slider on frontpage on mobile
    mobile: occrp-frontpage-2-mobile-portrait-1x.png
    tablet: occrp-frontpage-2-mobile-portrait-1x.png
    laptop: occrp-frontpage-2-mobile-portrait-1x.png
    desktop: occrp-frontpage-2-mobile-portrait-1x.png
  - name: The OCCRP frontpage on mobile
    mobile: occrp-frontpage-mobile-portrait-1x.png
    tablet: occrp-frontpage-mobile-portrait-1x.png
    laptop: occrp-frontpage-mobile-portrait-1x.png
    desktop: occrp-frontpage-mobile-portrait-1x.png
  - name: The OCCRP archive page on mobile
    mobile: occrp-archive-mobile-portrait-1x.png
    tablet: occrp-archive-mobile-portrait-1x.png
    laptop: occrp-archive-mobile-portrait-1x.png
    desktop: occrp-archive-mobile-portrait-1x.png
---

{% extends "../templates/portfolio.swig" %}
